version: "3"

services:
  mongo_db:
    container_name: mongo
    ports:
      - 8002:27017
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 5000:3000
    environment:
      APP_NAME: NodeServer
      PORT: 3000
      DB_URI: mongodb://mongo_db:27017/docker
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
